### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by Codeloper** [Codeloper/braingain-management#3]
- [x] UserView (Anpassen der Berechtigungen)
- [x] User durch admin anlegen/verwalten
- [x] CustomerView Dialog fixen
- [x] Kontingente löschen
- [x] Bemerkung in Person in view einbauen
- [x] Anmeldung
- [x] Views für die Tutoren
- [x] Statistik View
- [ ] Jahresabrechnung
- [x] Stunden mit Nachkommastellen
- [x] Auf der Rechnung Gesamtzahl Stunden
- [x] Fachniveau
- [ ] Passwort ändern für Tutor selbst
- [ ] (Schüler mit eindeutiger Rechnungsnummer (nicht einzeln pro Rechnung))
- [x] Header Fixen
